// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injector

import (
	"github.com/IJ4L/internal/graph/resolvers"
	"github.com/IJ4L/internal/repository"
	"github.com/IJ4L/internal/usecase"
	"github.com/IJ4L/pkg/db/postgres"
	"github.com/IJ4L/pkg/utils"
)

// Injectors from wire.go:

func InitializeResolver(cfg utils.Config) (*resolver.Resolver, error) {
	pool, err := postgres.InitDB(cfg)
	if err != nil {
		return nil, err
	}
	userRepository := repository.NewUserPgRepository(pool)
	userUsecase := usecase.NewUserUsecase(userRepository)
	resolverResolver := resolver.NewResolver(userUsecase)
	return resolverResolver, nil
}
